# Generated by Django 4.2.3 on 2023-07-20 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadTest',
            fields=[
                ('image_field', models.ImageField(upload_to='images/test_image_folder')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
