# Generated by Django 4.2.3 on 2023-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_imageuploadtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile_pictures/default_profile.png', null=True, upload_to='images/profile_pictures'),
        ),
    ]
